apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-crawler
  labels:
    app: synergychat-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-api
  template:
    metadata:
      labels:
        app: synergychat-api
    spec:
      containers:
        - name: synergychat-api
          image: bootdotdev/synergychat-api:latest
          env:
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                   name: synergychat-api-configmap
                   key: API_PORT
          envFrom:
            - configMapRef:
               name: synergychat-crawler-configmap